// Copyright 2021 - 2023 Universität Tübingen, DKFZ, EMBL, and Universität zu Köln
// for the German Human Genome-Phenome Archive (GHGA)
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//

import { faCircleArrowRight } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { useState } from "react";
import {
  Button,
  Container,
  Modal,
  OverlayTrigger,
  Tooltip,
} from "react-bootstrap";
import { useNavigate } from "react-router-dom";

const Confirm2FA = () => {
  const navigate = useNavigate();
  const [showModal, setShowModal] = useState(false);
  const [showError, setShowError] = useState(false);
  const [inputted2FA, setInputted2FA] = useState("");
  const [disabledContinueButton, setDisabledContinueButton] = useState(true);

  const Lost2FAModal = (props: any) => {
    const [disabledNew2FAButton, setDisabledNew2FAButton] = useState(true);
    return (
      <Modal show={showModal} size="lg" onHide={() => setShowModal(false)}>
        <Modal.Header>
          <Modal.Title>Create new setup for authenticator app</Modal.Title>
        </Modal.Header>
        <Modal.Body>
          <p>
            In the case that you lost your phone or the setup of your
            authenticator app, you can create a new authentication code setup.
          </p>
          <p className="fw-bold">
            However, all contact addresses that had been verified before will
            need to be verified again
          </p>

          <div>
            <input
              type="checkbox"
              id="agree"
              className="me-2"
              onChange={(e) => {
                setDisabledNew2FAButton(!e.target.checked);
                console.log(e.target.checked);
              }}
            />
            <label htmlFor="agree" className="d-inline">
              I acknowledge that all previous contact addresses will require
              re-verification if a new authenticator setup is requested
            </label>
          </div>
          <br />
          <Button
            disabled={disabledNew2FAButton}
            onClick={() => {
              navigate("/setup-2fa");
            }}
          >
            <FontAwesomeIcon icon={faCircleArrowRight} />
            &nbsp; Continue
          </Button>
          <Button
            variant="gray"
            className="ms-2 text-white"
            onClick={() => setShowModal(false)}
          >
            Cancel
          </Button>
        </Modal.Body>
      </Modal>
    );
  };

  return (
    <Container className="mt-4">
      <h2>Two-factor authentication</h2>
      <Lost2FAModal />
      <div className="w-100">
        <p>
          Please enter the 6-digit authentication code generated by your
          authenticator app
        </p>
        <form
          onSubmit={(e) => {
            e.preventDefault();
            if (inputted2FA === "123456") navigate("/");
            else setShowError(true);
          }}
        >
          <OverlayTrigger
            placement="right"
            overlay={<Tooltip>Invalid code entered</Tooltip>}
            rootClose={true}
            show={showError}
          >
            <input
              type="text"
              className="text-center fs-2"
              style={{ letterSpacing: "0.5em", paddingLeft: "0.5em" }}
              required
              minLength={6}
              maxLength={6}
              pattern="[0-9]{6}"
              size={6}
              onKeyDown={(e) => {
                if (
                  e.key.match("^[^0-9]{1}$") &&
                  e.ctrlKey === false &&
                  e.altKey === false
                )
                  e.preventDefault();
              }}
              onChange={(e) => {
                setInputted2FA(e.target.value);
                if (e.target.value.length === 6)
                  setDisabledContinueButton(false);
                else setDisabledContinueButton(true);
              }}
            />
          </OverlayTrigger>
          <div className="mt-4">
            <Button type="submit" disabled={disabledContinueButton}>
              <FontAwesomeIcon icon={faCircleArrowRight} />
              &nbsp; Submit
            </Button>
            <Button
              variant="secondary"
              className="ms-2 text-white"
              onClick={() => setShowModal(true)}
            >
              I lost my authenticator setup
            </Button>
          </div>
        </form>
      </div>
    </Container>
  );
};

export default Confirm2FA;
