# config parameters for development
host: 0.0.0.0
port: 8080
mass_url: "api/mass"
metldata_url: "api/metldata"
ars_url: "api/ars"
users_url: "api/auth/users"
wps_url: "api/wps"
default_data_access_duration_days: 365
