# config parameters for development
host: 0.0.0.0
port: 8080
mass_url: "http://127.0.0.1:8080/api/mass"
metldata_url: "http://127.0.0.1:8080/api/metldata"
ars_url: "http://127.0.0.1:8080/api/ars"
users_url: "http://127.0.0.1:8080/api/auth/users"
wps_url: "http://127.0.0.1:8080/api/wps"
default_data_access_duration_days: 365
