# config parameters for development
host: localhost
port: 8080
svc_search_url: "http://127.0.0.1:8001"
svc_repository_url: "http://127.0.0.1:8002"
svc_users_url: "http://127.0.0.1:8000/api/auth/users"
