#!/bin/bash

# create self-signed certificate for testing with the browser

HOST=data.ghga-dev.de
CERTFILE=cert.pem
KEYFILE=key.pem
ENVFILE=local.env
CLIENT_ID=oidc-client-id
BASIC_AUTH=username:password

cd /workspace/.devcontainer

test ! -f "$CERTFILE" -o ! -f "$KEYFILE" && \
  openssl req -x509 -newkey rsa:4096 -days 356 \
    -out "$CERTFILE" -keyout "$KEYFILE" \
    -subj "/CN=$HOST" -nodes \
    -addext "subjectAltName=DNS:$HOST,DNS:localhost"

# also add local environment that makes use of this

test ! -f "$ENVFILE" && echo "\
HTTPS=true
SSL_CRT_FILE=.devcontainer/$CERTFILE
SSL_KEY_FILE=.devcontainer/$KEYFILE
DATA_PORTAL_UI_HOST=$HOST
DATA_PORTAL_UI_PORT=443
REACT_APP_CLIENT_URL=https://$HOST/
REACT_APP_OIDC_CLIENT_ID=$CLIENT_ID # please adapt
REACT_APP_BASIC_AUTH=$BASIC_AUTH # please adapt" > "$ENVFILE"
