#!/bin/bash
# install web app in dev container

cd /workspace

# install web app dependencies:
npm install

# install helper script dependencies:
pip install -r ./configure_build_serve/requirements.txt

cd .devcontainer

# create certificates
./create_cert

# setup hosts file
pip install dnspython==2.3.0
sudo $(which python) ./setup_hosts.py
