version: "3"

services:
  # data portal ui

  data_portal_ui_svc:
    image: ghga/data-portal-ui:main
    environment:
      DATA_PORTAL_UI_HOST: 0.0.0.0
      DATA_PORTAL_UI_PORT: 8080
      WDS_SOCKET_PORT: 8080
    ports:
      - 8080:8080
    env_file:
      - local.env
