version: '3.2'
services:
  data_portal_ui_svc:

    build:
      context: .
      dockerfile: ./Dockerfile

    command: /bin/sh -c "while sleep 1000; do :; done"

    environment:
      DATA_PORTAL_UI_HOST: 0.0.0.0
      DATA_PORTAL_UI_PORT: 8080

    ports:
      - 8000:8080
      - 443:8080

    volumes:
      - ..:/workspace:cached
