version: "3"

services:
  # Data Portal UI
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        # Python version: 3, 3.11, 3.12
        VARIANT: 3.11
        # Install Node.js
        INSTALL_NODE: "true"
        NODE_VERSION: "lts/*"
        # on Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000
        USER_UID: 1000
        USER_GID: 1000

    init: true
    privileged: true

    volumes:
      - ..:/workspace:cached

    # override default command so things don't shut down after the process ends
    command: sleep infinity

    # use a non-root user for all processes
    user: vscode

    # define environment variables
    environment:
      DATA_PORTAL_UI_CONFIG_YAML: /workspace/.devcontainer/.data_portal_ui.yaml

    env_file:
      - local.env
