version: "3"

services:
  # data portal ui

  data_portal_ui_svc:
    image: ghga/data-portal-ui:main
    environment:
      DATA_PORTAL_UI_HOST: 127.0.0.1
      DATA_PORTAL_UI_PORT: 8080
      WDS_SOCKET_PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - metadata_search_svc
      - metadata_rep
    env_file:
      - local.env

  # metadata search

  metadata_search_svc:
    image: ghga/metadata-search-service:main
    environment:
      METADATA_SEARCH_SERVICE_HOST: 0.0.0.0
      METADATA_SEARCH_SERVICE_PORT: 8080
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_ORIGINS: '["*"]'
      METADATA_SEARCH_SERVICE_CORS_ALLOW_CREDENTIALS: "true"
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_METHODS: '["*"]'
      METADATA_SEARCH_SERVICE_CORS_ALLOWED_HEADERS: '["*"]'
      METADATA_SEARCH_SERVICE_LOG_LEVEL: debug
      METADATA_SEARCH_SERVICE_DB_URL: mongodb://metadata_db:27017
      METADATA_SEARCH_SERVICE_DB_NAME: metadata
    entrypoint: ["sh", "-c"]
    command: |
      '''
      # install additional deps as they are needed for the population script;
      cd /service
      pip install ".[all]"

      # run the service:
      metadata-search-service
      '''
    ports:
      - 127.0.0.1:8001:8080
    depends_on:
      - metadata_db

  # metadata population

  metadata_pop:
    image: ghga/metadata-populate-job:main
    environment:
      DATA_DB_NAME: metadata
      DATA_DB_URL: mongodb://metadata_db:27017
    entrypoint: ["bash", "-c", "./clean-data.sh && ./populate-data.sh"]
    env_file:
      - local.env
    depends_on:
      - metadata_db

  # metadata repo

  metadata_rep:
    image: ghga/metadata-repository-service:main
    environment:
      METADATA_REPOSITORY_SERVICE_HOST: 0.0.0.0
      METADATA_REPOSITORY_SERVICE_PORT: 8080
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_ORIGINS: '["*"]'
      METADATA_REPOSITORY_SERVICE_CORS_ALLOW_CREDENTIALS: "true"
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_METHODS: '["*"]'
      METADATA_REPOSITORY_SERVICE_CORS_ALLOWED_HEADERS: '["*"]'
      METADATA_REPOSITORY_SERVICE_LOG_LEVEL: debug
      METADATA_REPOSITORY_SERVICE_DB_URL: mongodb://metadata_db:27017
      METADATA_REPOSITORY_SERVICE_DB_NAME: metadata

    entrypoint: ["metadata-repository-service"]
    ports:
      - 127.0.0.1:8002:8080
    depends_on:
      - metadata_db

  # mongo db

  metadata_db:
    image: mongo:5.0.4
    volumes:
      - metadata_db_fs:/data/db
    ports:
      - 27000:27017

volumes:
  metadata_db_fs: {}
